### ISSUE TITLE
New blockchain left miners holding worthless coins after week of mining

### ISSUE THREAD

**Issue by mrknc** [Beldex-Coin/beldex#1]
Hello, ladies and gentlemen of beldex. Since you are not replying to email, we are trying to contact you here. We run fairhash.org group of pools. Your decision to switch blockchains with no warning has cost miners tens of thousands of dollars. Given the fact that you have awarded yourself 100 million beldex on the new blockchain, there is no good reason for you to leave miners and exchanges without compensation for their effort/investment. If you need technical help, we are willing to work with you to help resolving this unfortunate situation. If not, we will have to outline our version of events online and in social media. This will be very visible and unfortunate for all the parties involved.  Please contact us.

**Comment by mrknc** [comment]
Hello, Niyas. We have submitted the form for the pool wallet. It's obviously impossible to list all the transactions in the pool wallet, there are thousands of them, but we did include quite a few mining txs to illustrate it is a pool wallet. Currently fairhash beldex pool balance is over 14k on the old blockchain. Hopefully, we will receive it on the new blockchain, so it can be distributed to the miners.

Also, be advised that a lot of miners have most of their balances in btc-alpha exchange already. It is paramount for the exchange to be compensated for their balances on the new blockchain. If they delist and release their beldex coins on the new blockchain, you will still have a lot of very angry beldex owners and will have to start the process of collecting wallet info again. 

As I stated before, if you need technical help sorting this out, please do not hesitate to contact us. There is really no reasons that this whole situation cannot be worked out.

**Comment by niyas-beldex** [comment]
Hi mrknc,
The miners who are having balances in btc-alpha can also submit the request form along with the BDX balance and transaction screenshot from btc-alpha. We have mentioned this in our post on social media channels.

**Comment by niyas-beldex** [comment]
I am closing this issue as we agreed to deposit the old blockchain balances.

**Comment by mrknc** [comment]
I haven't heard a single case of reimbursing old blockchain balance so far. We have lost 14000 coins in the wallet and 25000 in exchange. This is far from closed issue

**Comment by niyas-beldex** [comment]
We have restored coins in BTC-Alpha exchange. Regarding the the coins in the wallet, we got lot of request through google form and we are processing those. Will deposit your coins.

**Comment by mrknc** [comment]
So you haven't even paid out people from previous blockchain swap, yet you are planning to move to another blockchain yet again? I guess you just create a new blockchain, sell the giant premine, then start another blockchain.
