### ISSUE TITLE
beldex-win-x64-4.1.0.zip is malware

### ISSUE THREAD

**Issue by khanosama783** [Beldex-Coin/beldex#112]
this file contain malware "beldex-win-x64-4.1.0.zip" please look. Virustotal Site: https://www.virustotal.com/gui/file/1237c6a87ae02be9ee4bd8d140f2597477444f875cd85c1063ec1aa05314852e
![Screenshot 2023-07-13 161514](https://github.com/Beldex-Coin/beldex/assets/51233466/c4a8ec08-bbe0-4f89-a131-1ab3d0f0b4b7)

**Comment by sanada08** [comment]
Thanks @khanosama783. We will check and reproduce with file with new hash.

**Comment by sanada08** [comment]
new version hardfork fixed this issue.
