### ISSUE TITLE
MASTERNODE NOT WORKING ANS SHOWING

### ISSUE THREAD

**Issue by RAMANARUMUGAM** [Beldex-Coin/beldex#118]
MY MASTERNODE IS ACCIDENTALLY DELETED BY AN ERROR.I CONTRIBUTE 10000BDX FOR THAT BUT I CANT GET MY COINS BACK.PLEASE HELP MR TO GET MY CONTRIBUTED COINS IN MY BELDEX WALLET.THAKYOU

**Comment by victor-tucci** [comment]
If your master node is deleted, your node will be unable to submit the proof to the network, leading to its decommission. Once it is deregistered, you can expect to receive the staked coins after approximately 30 days.
