### ISSUE TITLE
Master node not registering to network after updating code from 3.1.3 to 3.1.4

### ISSUE THREAD

**Issue by thangamani88** [Beldex-Coin/beldex#20]
Hi Team,

I was running the master node(with Staking) on code verison 3.1.3 and recently due to the update the nodes were de-registered from the network. So, I had taken the new version 3.1.4 to run the masternode. But with the new version the master node is not registering to the network. Please advise.

Attaching the screenshots of the logs.
![image](https://user-images.githubusercontent.com/51872949/62612702-8a7eb900-b925-11e9-8410-ae7f6f32a10c.png)
![image (1)](https://user-images.githubusercontent.com/51872949/62612713-923e5d80-b925-11e9-8b57-211d73dea1ee.png)

**Comment by thangamani88** [comment]
Requesting @sanada08 @scilicet64  to check this and suggest.

**Comment by sanada08** [comment]
please attach log with log ```set-log 1``` in daemon.

**Comment by thangamani88** [comment]
@sanada08 attaching the logs.

[beldexlogs.log](https://github.com/Beldex-Coin/beldex/files/3480116/beldexlogs.log)

**Comment by sanada08** [comment]
@thangamani88, Have you removed .beldex directory and synced freshly. If so, new Master node public key will be created. If you haven't removed. Please don't stop the node  run daemon with set-log 1 for a day. If you have any issue attach the log file.

**Comment by thangamani88** [comment]
@sanada08 I have not removed the .beldex directory. The new version node  is running for 3-4 days without registering to network. How should I proceed?

**Comment by sanada08** [comment]
@thangamani88, Let the node run for a day with set-log 2. and attach the log here. So that we can trace what issue might be.

**Comment by thangamani88** [comment]
I have already started the node with log level 1, should I change it to 2 now?

**Comment by sanada08** [comment]
Yes, log 2  gives more details about the node.

**Comment by thangamani88** [comment]
[beldex.log](https://github.com/Beldex-Coin/beldex/files/3480892/beldex.log)
@sanada08 attaching the logs generated till now. Please check if any issue can be found here.

**Comment by sanada08** [comment]
Thanks, We will look into it

**Comment by thangamani88** [comment]
[beldex (1).zip](https://github.com/Beldex-Coin/beldex/files/3482340/beldex.1.zip)
@sanada08  attaching the logs generated till now. Please check.

**Comment by thangamani88** [comment]
Hi @sanada08 any update?

**Comment by thangamani88** [comment]
@sanada08 @scilicet64 

Please give an update.

**Comment by sanada08** [comment]
We were analyzing the cause. Will give you an update once finished.

**Comment by thangamani88** [comment]
@sanada08 @scilicet64 any update on the root cause?

**Comment by thangamani88** [comment]
@sanada08 @scilicet64 please update.

**Comment by thangamani88** [comment]
@sanada08  @scilicet64  please update.
--

**Comment by thangamani88** [comment]
Please update

**Comment by thangamani88** [comment]
@sanada08 @scilicet64 Please update if this issue can be fixed. 50,000 BDX are stuck in the masternodes.

**Comment by scilicet64** [comment]
Please use print_locked_stakes to check current status

Use 
request_stake_unlock ENTER_MN_KEY

To unlock the stake if not already done.
This will take 15 days normally. When they are gone offline because of failure (not updated during the fork) it will take 30 days.

**Comment by scilicet64** [comment]
In response to the original post:
I checked the log.

It seems the update to new version took more than 2 hours after fork. Then it will deregister.
A MN may not be offline for more than 2 hours.

Next time when we fork we must take more time and update the MN first before fork. I guess we had to do it like this because of the idcm listing and we had no luxury of waiting.

**Comment by thangamani88** [comment]
@scilicet64 thanks for the response:
 [wallet bxcMwz (has locked stakes)]:     print_locked_stakes
[wallet bxcMwz (has locked stakes)]:                                                 Wallet password: 
Blacklisted Stakes
  Unlock Height/Key Image: 148497/3bfadd42f749e4ce4a02dbf85f47e4a3ee1c4730db2

  Unlock Height/Key Image: 148497/3bfadd42f749e4ce4a02dbf85f47e4a3ee1c4730db2

  Unlock Height/Key Image: 148497/3bfadd42f749e4ce4a02dbf85f47e4a3ee1c4730db2

  Unlock Height/Key Image: 148497/3bfadd42f749e4ce4a02dbf85f47e4a3ee1c4730db2

 [wallet bxcMwz (has locked stakes)]:     request_stake_unlock 1c4d039573d4a083e6fcf211a1078533a154f7c3868ae4b6b00de686c4fd3285
[wallet bxcMwz (has locked stakes)]:                                                 Wallet password: 
Error: No master node is known for: 1c4d039573d4a083e6fcf211a1078533a154f7c3868ae4b6b00de686c4fd3285

I'm unable to request stake unlock as the master node has already de-registered. Does this mean the stakes will be unlocked after 30 days from the day of master node de-registeration? Please confirm.

And also what would the best practice to be followed from our side when there is a fork again in the beldex network. Will this issue be fixed in next master node update or will this issue continue in next update as well if the node is not updated in 2 hours?

**Comment by scilicet64** [comment]
The 30 days penalty is by design in Master node, so this is not an issue and will not be “fixed”. It is requires as incentive for MN to stay up and deliver quality uptime.
Best practice is update MN before fork, so there will be near zero downtime.


148497-137238=11259 blocks from now
375 hours= about 15.6 days

**Comment by thangamani88** [comment]
@scilicet64 will the staking be unlocked automatically after 30 Days?

**Comment by jakevault** [comment]
> The 30 days penalty is by design in Master node, so this is not an issue and will not be “fixed”. It is requires as incentive for MN to stay up and deliver quality uptime.
> Best practice is update MN before fork, so there will be near zero downtime.
> 
> 148497-137238=11259 blocks from now
> 375 hours= about 15.6 days

Thanks a lot for the clarification. We appreciate all of your efforts. 
Kindly guide what would be the next step or outcome ?   
Will our masternodes work fine after that stipulated time specified by you? or should we have to unstake and stake again. ? thanks again.

**Comment by scilicet64** [comment]
After the mentioned 15.6 days the coins are free to use. So you can choose to start a MN again.
It will not stake automatically. So when the coins are free/unlocked you have to start staking yourself.

**Comment by jakevault** [comment]
Cool. Thanks for the response.

**Comment by sanada08** [comment]
+resolved.

**Comment by thangamani88** [comment]
How do we know in advance about the fork or  master node updates?

**Comment by sanada08** [comment]
Will be announced in social media channel, a week or 2 days prior to the fork.
