### ISSUE TITLE
Beldex-cli output broken in 3.1.5

### ISSUE THREAD

**Issue by SharkWipf** [Beldex-Coin/beldex#23]
After updating the Linux wallet to 3.1.5, the console output is all over the place.
See attached screenshots (sensitive data edited out).

![image](https://user-images.githubusercontent.com/751205/86605790-70bb7b00-bfa7-11ea-8563-7655fc8483de.png)

![image](https://user-images.githubusercontent.com/751205/86605969-ab251800-bfa7-11ea-9aeb-6500dd283df9.png)

**Comment by sanada08** [comment]
Reopen if issue exits
