### ISSUE TITLE
Wallet CLI performance issue

### ISSUE THREAD

**Issue by codeman-crypto** [Beldex-Coin/beldex#71]
The wallet CLI is taking too much time to load a wallet. This issue happens only for the wallet which has lakhs of transactions in it. 

**Note:** need to work on ```simplewallet.cpp```

**Comment by Alexsanchez06** [comment]
I will look into this issue.

**Comment by Alexsanchez06** [comment]
while checking the wallet-cli. I seen many logs in the **node_rpc_proxy.cpp** file 

`bool NodeRPCProxy::get_height(uint64_t &height) const
{
  LOG_PRINT_L0("NodeRPCProxy::get_height");
  auto now = std::chrono::steady_clock::now();
  if (now >= m_height_time + 30s) // re-cache every 30 seconds
    if (!get_info())
      return false;
  LOG_PRINT_L0("NodeRPCProxy::get_height:" << m_height);
  height = m_height;
  return true;
}`.

`std::optional<uint8_t> NodeRPCProxy::get_hardfork_version() const
{
    LOG_PRINT_L0("get_hardfork_version");
    if (m_offline)
       return std::nullopt;
    LOG_PRINT_L0("invoke HARD_FORK_INFO");
    auto now = std::chrono::steady_clock::now();`

here the **LOG_PRINT_L0** may slow down the wallet while refreshing the wallet.
so I am looking into it.

**Comment by sanada08** [comment]
Has some LOG_PRINT_L0 in noderpcproxy::get_info

```bool NodeRPCProxy::get_info() const
{
  if (m_offline) return false;
  LOG_PRINT_L0("get_info");
  auto now = std::chrono::steady_clock::now();
  if (now >= m_get_info_time + 30s) // re-cache every 30 seconds
  {
    try {
      auto resp_t = invoke_json_rpc<rpc::GET_INFO>({});
      m_height = resp_t.height;
      LOG_PRINT_L0("GET_INFO success" << m_height);
      m_target_height = resp_t.target_height;
      m_block_weight_limit = resp_t.block_weight_limit ? resp_t.block_weight_limit : resp_t.block_size_limit;
      m_immutable_height = resp_t.immutable_height;
      m_get_info_time = now;
      m_height_time = now;
    } catch (...) {
        LOG_PRINT_L0("GET_INFO failed");
        return false; }
  }
  return true;
}```
Could you try to converting the LO to L3. Log level helpful.

**Comment by codeman-crypto** [comment]
@Alexsanchez06 What is the time metrics before and after removing of L0 logs..

**Comment by Alexsanchez06** [comment]
when I tested it takes up to 90 - 120 seconds to load a wallet. After the log removal, the wallet performance is much better it takes only 2-3 seconds.

**Comment by Alexsanchez06** [comment]
when using the LOG_PRINT_L3  it slows the wallet when running in log level 3 mode. so I think the better solution will be to remove the unnecessary logs.

**Comment by Alexsanchez06** [comment]
#72   pull request for wallet performance

**Comment by codeman-crypto** [comment]
@Alexsanchez06 Send me your BDX wallet address

**Comment by Alexsanchez06** [comment]
**bxd193yhdgtiLgLKZcxsEcaSTmgggSzt7gk4GRW8kRicKxLK5jQwaHsFYFXH9uPvzg53DXCnp4L9sdXYsunT8RKb2Sf4QgRaE**  
this is my beldex wallet @codeman-crypto

**Comment by codeman-crypto** [comment]
@Alexsanchez06 1000 BDX has been transferred to your wallet for this contribution.

https://explorer.beldex.io/tx/ffb2190d9c0849835c5a025ba6c22b807bde5809fbce4a2be27fe2df646d81d3

**Comment by Alexsanchez06** [comment]
I got my contribution reward @codeman-crypto
