### ISSUE TITLE
unlock stake

### ISSUE THREAD

**Issue by Aleksey-Solin** [Beldex-Coin/beldex#73]
Hosting for nodes removed the node on which I was doing the stake . My stake is currently blocked. How do I unlock my stake?

**Comment by sanada08** [comment]
check the mn pub key in [explorer](https://explorer.beldex.io) it will show you number of days remaining, after that your wallet will be credited with the staked BDX

**Comment by Aleksey-Solin** [comment]
> check the mn pub key in [explorer](https://explorer.beldex.io/) it will show you number of days remaining, after that your wallet will be credited with the staked BDX

I would like to find this masternode key, but: 

1. The hosting provider has deleted all the information about the masternode  (https://pecuniaplatform.io)
2. In my wallet, in the "my stake" section, information about my stake and about the masternode is not loaded. This is not present even after the wallet is fully synchronized.

**Comment by codeman-crypto** [comment]
Please take this issue to pecunia platform.. They will be the right people to solve this..
