### ISSUE TITLE
Multiple masternode setup in single VPS

### ISSUE THREAD

**Issue by sanada08** [Beldex-Coin/beldex#79]
Should setup the multiple masternode in single VPS, currently we can setup the single mn in single VPS.

**Comment by victor-tucci** [comment]
multiple-master-node-setup are working smoothly in testing. but it's up to user risk. when a server went down all the setup  MN are goes down.

**Comment by victor-tucci** [comment]
https://github.com/Beldex-Coin/beldex-multi-mn/pull/1  This is the pull request for the multiple-master-node setup

**Comment by victor-tucci** [comment]
[https://github.com/Beldex-Coin/beldex-multi-mn/pull/1](url)
