### ISSUE TITLE
Suggestion: Donating to ETH-XMR Atomic Swap Development 

### ISSUE THREAD

**Issue by ShawnOrwell** [Beldex-Coin/beldex#84]
Atomic swaps help adding an additional layer of privacy to XMR and ETH swap. 

The team has been working on ETH-XMR atomic swap, you can find the source code of the project here - https://github.com/AthanorLabs/atomic-swap

The project looks promising, however they need funding to continue its development. Magic Monero Grants has started a campaign to raise funds to this cause. Here's the link to the campaign: https://magicgrants.org/noot-ETH-XMR-Atomic-Swaps/ 

Since we have been working to advance privacy in crypto, I believe donation to this cause will be appropriate. What are your thoughts? @codeman-crypto & @sanada08 could we make a donation?

**Comment by sanada08** [comment]
Hey @ShawnOrwell , thanks for the information.

**Comment by codeman-crypto** [comment]
The project looks good. For the first round of donation we can do $2000 worth of BDX.

**Comment by ShawnOrwell** [comment]
Sounds great! However, Magic Monero Grants would not be able to process a donation in BDX since BDX isn't listed on a U.S. based exchange. 

They can accept crypto donations in BTC, ETH, and XMR.

**Comment by codeman-crypto** [comment]
Ok then we can do it using XMR.

**Comment by ShawnOrwell** [comment]
Payment of $2000 USD in XMR has been made to the following address on the campaign's budibase form. 

Link to MAGIC Monero Fund Crypto Donations: https://magicgrants.budibase.app/app/magic-monero-fund-donations#/home 

Hash for the payment: 4b7013905157f3d71e7775522b75eff2ed65d4e451839a28d33db2aeded65470

You can find the payment updated on the campaign's GoFundMe page here: https://www.gofundme.com/f/noot-ethxmr-atomic-swap-development-4-months
